            global      _start
            section     .text

_start:
            mov         rax, 1          ; print...
            mov         rdi, 1          ; ...to stdout...
            mov         rsi, msg        ; ...this text...
            mov         rdx, msglen     ; ...with this size...
            syscall                     ; ...GO!

            mov         rax, 60         ; exit...
            mov         rdi, 0          ; ...successfully...
            syscall                     ; ...GO!

            section     .data
msg:        db          "Hello, World!", 10
msglen      equ         $-msg