[package]
name = "hug_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hug_transpiler = { path = "../hug_transpiler" }
hug_lib = { path = "../hug_lib" }
asmpeach = "0.1.*"