[package]
name = "hug_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hug_ast = { path = "../hug_ast" }
hug_lib = { path = "../hug_lib" }